### ISSUE TITLE
when I load deeplabcut file xx.h5, it shows an import error.

### ISSUE THREAD

**Issue by nsaids** [PolarBean/DLC_ROI_tool#2]
when I load deeplabcut file xx.h5, it shows an import error.
ImportError: Missing optional dependency 'tables'
although I have already installed 'tables'.
And, I also uninstalled and reinstalled tables, it didn't wort.
OS: win10  use anaconda   pandas:0.25.3 tables:3.6.1 
```
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2032.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\Administrator\DLC_ROI_tool\ROI_tool.py", line 192, in load_deeplab_Coords
    self.data=pd.read_hdf(path)
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pandas\io\pytables.py", line 397, in read_hdf
    store = HDFStore(path_or_buf, mode=mode, errors=errors, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pandas\io\pytables.py", line 518, in __init__
    tables = import_optional_dependency("tables")
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pandas\compat\_optional.py", line 92, in import_optional_dependency
    raise ImportError(msg) from None
ImportError: Missing optional dependency 'tables'.  Use pip or conda to install tables.

```

**Comment by PolarBean** [comment]
hey thanks for using my tool. did you install tables using 'conda install tables'

**Comment by PolarBean** [comment]
To avoid these kinds of dependency problems in the futurem I recommend installing them with our packaged yml file. just cd into our cloned directory and run
 

`conda env create -f ROI_ENV.yml`

**Comment by PolarBean** [comment]
Hey Im going to assume this fixed it and close this issue. If not feel free to reopen :)
